chore(spec): make TS/styled-components example build
...instead of failing with error message:

```
[tsl] ERROR in ./packages/spec/integration/typescript-styled-components/index.tsx(13,7)
      TS2322: Type '{ children: string; css: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'.
  Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'.
```